services:
  backend_app:
    image: node:latest
    container_name: VT6003CEM_backend_app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - type: bind
        source: ./code
        target: /app
    ports:
      - 8081:8081
    environment:
      - NODE_ENV=development
      - PORT=8081
      - TZ=UTC
    command: > 
      sh -c "
        npm install &&
        npm run build &&
        npm run migrate &&
        npm run dev
      "
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:latest
    container_name: VT6003CEM_postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backstage
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: