services:
  backend:
    image: node:latest
    container_name: VT6003CEM_backend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - type: bind
        source: ./code
        target: /app
    ports:
      - 8081:8081
    environment:
      - NODE_ENV=development
      - PORT=8081
      - TZ=UTC
    command: > 
      sh -c "
        npm install &&
        npm run dev
      "